### ISSUE TITLE
SINCLAIR: Inital GEX Workflow

### ISSUE THREAD

**Issue by slsevilla** [CCBR/SINCLAIR#5]
Workflow
- [x] Check manifest
- [x] Create cellranger count manifest
- [x] Run Cell ranger count
- [x] Run scnra.R file
- [x] Run merged object (https://github.com/CCBR/TechDev_scRNASeq_Dev2023/issues/10)
- [x] Run batch correction seurat
- [x] Run batch correction harmony
- [x] Run batch correction rpca
- [x] Run batch correction scvi (https://github.com/CCBR/SINCLAIR/issues/23)
- [x] Run batch correction liger (https://github.com/CCBR/SINCLAIR/issues/22)
- [x] Run batch correction merge (script named integration)
